version: '3'

services:
  web:
    image: winterant/lduoj:2.0
    restart: always
    ports:
      - 8080:80
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=lduoj
      - DB_USERNAME=oj_user
      - DB_PASSWORD=OurFuture2045
      - JUDGE0_SERVER=judge0-server:2358
      - QUEUE_CONNECTION=database
      # [Production]
      # - HREF_FORCE_HTTPS=true  # If using https but web page can't fetch static files, open it.
      # [Local]
      # - APP_DEBUG=true  # Open debug mode for laravel
    volumes:
      # [Production]
      - ./data/web/storage/app:/app/storage/app
      - ./data/web/storage/logs:/app/storage/logs
      # - ./data/web/public/favicon.ico:/app/public/favicon.ico:ro  # Customized favicon.ico
      # [Local]
      # - ./data/web:/app  # Mount entire project to host machine.

  mysql:
    image: docker.io/mysql:8.0
    restart: always
    command:
      --authentication_policy=mysql_native_password
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: OurFuture2099
      MYSQL_USER: oj_user
      MYSQL_PASSWORD: OurFuture2045
      MYSQL_DATABASE: lduoj
    volumes:
      - ./data/mysql:/var/lib/mysql

  judge0-server:
    image: judge0/judge0:1.13.0
    restart: always
    privileged: true
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    # ports:
    #   - 2358:2358

  jduge0-workers:
    image: judge0/judge0:1.13.0
    restart: always
    privileged: true
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro

  judge0-db:
    image: postgres:13.0
    restart: always
    env_file: ./judge0.conf
    volumes:
      - ./data/judge0/postgres:/var/lib/postgresql/data

  judge0-redis:
    image: redis:6.0
    restart: always
    env_file: ./judge0.conf
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    volumes:
      - ./data/judge0/redis:/data
