version: '3'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  web:
    image: winterant/lduoj:2.0
    container_name: lduoj-web
    restart: always
    ports:
      - 8080:80
    env_file: lduoj.conf
    logging: *default-logging
    volumes:
      # 自定义网站图标（./data/favicon.ico 是你的图片）
      # - ./data/favicon.ico:/app/public/favicon.ico:ro
      # 挂载宿主机目录以永久保存网站数据（生产环境使用）
      - ./data/web/storage:/app/storage
      # 挂载宿主机目录以永久保留源代码和数据（仅开发人员使用，与上一条不能同时启用）
      # - ./data/web:/app

  go-judge:
    image: winterant/go-judge:1.0
    container_name: lduoj-go-judge
    restart: always
    shm_size: 512m
    environment:
      - ES_FILE_TIMEOUT=10m
    privileged: true
    logging: *default-logging
    volumes:
      - ./data/web/storage/app/data:/testdata:ro

  mysql:
    image: docker.io/mysql:8.0
    container_name: lduoj-mysql
    restart: always
    security_opt:
      - seccomp:unconfined # docker取消安全验证
    command:
      --max_connections=1024
      --thread_cache_size=256
      --authentication_policy=mysql_native_password
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --log_bin_trust_function_creators=1
    env_file: lduoj.conf
    logging: *default-logging
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: lduoj-redis
    restart: always
    env_file: lduoj.conf
    logging: *default-logging
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    volumes:
      - ./data/redis:/data
