name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

env:
  IMAGE_NAME: lduoj
  DOCKER_REGISTRY: winterant

jobs:
  build-image:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.output-id.outputs.v }}
    steps:
      - uses: actions/checkout@v3

      - id: output-id
        run: |
          VERSION=unknown
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "v=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        run: |
          echo ${{ steps.output-id.outputs.v }} > ./install/.version
        with:
          context: .
          file: ./install/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-id.outputs.v }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
